/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stok_takip_programi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CASPER
 */
public class urun_ekle extends javax.swing.JFrame {

    /**
     * Creates new form urun_ekle
     */
    private void UrunListeGuncelle(){
    
     try {
             String baslik[] = new String[]{"Kategori", "Ürün Adı", "Beden", "Renk", "Fiyat", "Adet", "Açıklama" };  
            Class.forName("com.mysql.jdbc.Driver");

            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/stok_takip", "root", "");
            
            st = con.createStatement();                
            rs = st.executeQuery("select * from urunler");
            rs.last();
           
            int kayitsayisi = rs.getRow();
            rs.beforeFirst();

            Object data[][] = new Object[kayitsayisi][];
            int i = 0;

            while (rs.next()) {

                data[i] = new Object[]{  
                    
                    rs.getString("kategori"),  
                    rs.getString("urunadi"),
                    rs.getString("beden"),
                    rs.getString("renk"),  
                    rs.getString("fiyat"),
                    rs.getString("adet"),
                    rs.getString("aciklama"), 
                };
                i++;
            }
           
            con.close();
            urunler_tablosu.setModel(new DefaultTableModel(data, baslik));
            
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }
    }
    private static JFrame gelenform;
    public urun_ekle() {
        
        super("Ürün Ekleme Formu");       
      
        initComponents();
        
        
        
        UrunListeGuncelle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ekle = new javax.swing.JButton();
        lbl_kategori = new javax.swing.JLabel();
        lbl_adi = new javax.swing.JLabel();
        lbl_renk = new javax.swing.JLabel();
        lbl_fiyat = new javax.swing.JLabel();
        kategori_alani = new javax.swing.JTextField();
        fiyat_alani = new javax.swing.JTextField();
        renk_alani = new javax.swing.JTextField();
        ad_alani = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        urunler_tablosu = new javax.swing.JTable();
        guncelle = new javax.swing.JButton();
        sil = new javax.swing.JButton();
        lbl_renk1 = new javax.swing.JLabel();
        beden_alani = new javax.swing.JTextField();
        lbl_fiyat1 = new javax.swing.JLabel();
        adet_alani = new javax.swing.JTextField();
        lbl_fiyat2 = new javax.swing.JLabel();
        aciklama_alani = new javax.swing.JTextField();
        lbl_filtrele = new javax.swing.JLabel();
        arama_alani = new javax.swing.JTextField();
        arama = new javax.swing.JButton();
        cikis = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(853, 560));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        ekle.setText("Ürünü Ekle");
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleActionPerformed(evt);
            }
        });
        getContentPane().add(ekle);
        ekle.setBounds(160, 390, 100, 25);

        lbl_kategori.setText("Kategori");
        getContentPane().add(lbl_kategori);
        lbl_kategori.setBounds(20, 100, 70, 16);

        lbl_adi.setText("Ürün Adı");
        getContentPane().add(lbl_adi);
        lbl_adi.setBounds(20, 140, 70, 20);

        lbl_renk.setText("Renk");
        getContentPane().add(lbl_renk);
        lbl_renk.setBounds(20, 220, 80, 16);

        lbl_fiyat.setText("Fiyat");
        getContentPane().add(lbl_fiyat);
        lbl_fiyat.setBounds(20, 260, 70, 16);
        getContentPane().add(kategori_alani);
        kategori_alani.setBounds(110, 90, 170, 30);
        getContentPane().add(fiyat_alani);
        fiyat_alani.setBounds(110, 250, 170, 30);
        getContentPane().add(renk_alani);
        renk_alani.setBounds(110, 210, 170, 30);
        getContentPane().add(ad_alani);
        ad_alani.setBounds(110, 130, 170, 30);

        urunler_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        urunler_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urunler_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(urunler_tablosu);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 90, 520, 402);

        guncelle.setText("Güncelle");
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });
        getContentPane().add(guncelle);
        guncelle.setBounds(160, 420, 100, 25);

        sil.setText("Sil");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });
        getContentPane().add(sil);
        sil.setBounds(160, 450, 100, 25);

        lbl_renk1.setText("Beden");
        getContentPane().add(lbl_renk1);
        lbl_renk1.setBounds(20, 180, 70, 16);
        getContentPane().add(beden_alani);
        beden_alani.setBounds(110, 170, 170, 30);

        lbl_fiyat1.setText("Adet");
        getContentPane().add(lbl_fiyat1);
        lbl_fiyat1.setBounds(20, 300, 70, 16);
        getContentPane().add(adet_alani);
        adet_alani.setBounds(110, 290, 170, 30);

        lbl_fiyat2.setText("Açıklama");
        getContentPane().add(lbl_fiyat2);
        lbl_fiyat2.setBounds(20, 340, 80, 16);
        getContentPane().add(aciklama_alani);
        aciklama_alani.setBounds(110, 330, 170, 30);

        lbl_filtrele.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_filtrele.setText("Filtrele");
        getContentPane().add(lbl_filtrele);
        lbl_filtrele.setBounds(400, 50, 37, 17);
        getContentPane().add(arama_alani);
        arama_alani.setBounds(450, 40, 170, 30);

        arama.setText("Ara");
        arama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aramaActionPerformed(evt);
            }
        });
        getContentPane().add(arama);
        arama.setBounds(640, 40, 53, 25);

        cikis.setText("ÇIKIŞ");
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });
        getContentPane().add(cikis);
        cikis.setBounds(739, 20, 90, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stok_takip_programi/background.jpg"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(850, 550));
        jLabel1.setPreferredSize(new java.awt.Dimension(850, 550));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleActionPerformed
                
            String kategori=kategori_alani.getText();
            String adi=ad_alani.getText();
            String beden=beden_alani.getText();
            String renk=renk_alani.getText();
            String fiyat=fiyat_alani.getText();
            String adet=adet_alani.getText();
            String aciklama=aciklama_alani.getText();
                
            try {
                    
                if (kategori.equals("") || adi.equals("") || renk.equals("") || fiyat.equals("")) {

                    JOptionPane.showMessageDialog(this, "Lütfen Boş Alanları Doldurunuz!");

                } else {            
                    Class.forName("com.mysql.jdbc.Driver");

                    Connection con = null;
                    Statement st = null;
                    ResultSet rs = null;
                    
                    con = DriverManager.getConnection("jdbc:mysql://localhost/stok_takip", "root", "");
                    st = con.createStatement();
                    
                    String sql = "INSERT INTO urunler (kategori,urunadi,beden,renk,fiyat,adet,aciklama)" 
                            + " VALUES ('"+kategori+"', '"+adi+"', '"+beden+"', '"+renk+"', '"+fiyat+"', '"+adet+"', '"+aciklama+"')";

                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, adi + "  adlı ürün eklenmiştir.");
                    UrunListeGuncelle();
            
                }
            
            } catch (ClassNotFoundException ex) {
                 JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

            } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
            }  
            
            
        
    }//GEN-LAST:event_ekleActionPerformed

    private void aramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aramaActionPerformed
        
        String ara =arama_alani.getText();
        String baslik[] = new String[]{"Kategori", "Ürün Adı", "Beden", "Renk", "Fiyat", "Adet", "Açıklama" }; 

        try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = null;
            Statement st = null;
            ResultSet rs = null;
            
            con = DriverManager.getConnection("jdbc:mysql://localhost/stok_takip", "root", "");
            
            String sorgu ="select * from urunler where urunadi like '%"+arama_alani.getText()+"%' or"
                    +" kategori like '%"+arama_alani.getText()+"%' or"
                    +" beden like '%"+arama_alani.getText()+"%' or"
                    +" renk like '%"+arama_alani.getText()+"%' ";
            
            st = con.createStatement();
            rs = st.executeQuery(sorgu);
            
            rs.last();
           
            int say = rs.getRow();
            rs.beforeFirst();
 
            
            String sayi = null;                
            sayi = String.valueOf(rs.getRow());                

            if(say < 1){
                JOptionPane.showMessageDialog(null, "Aradığınız Ürün Bulunamadı!");
            }
            else{
                
                Object data[][] = new Object[say][];
                int i = 0;
                
                while (rs.next()) {

                    data[i] = new Object[]{ 
                        
                        rs.getString("kategori"),  
                        rs.getString("urunadi"),
                        rs.getString("beden"),
                        rs.getString("renk"),  
                        rs.getString("fiyat"),
                        rs.getString("adet"),
                        rs.getString("aciklama"),
                    };
                    i++;
                }
                urunler_tablosu.setModel(new DefaultTableModel(data, baslik));
            }
            
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }
        
    }//GEN-LAST:event_aramaActionPerformed

    private void urunler_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urunler_tablosuMouseClicked
        
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        PreparedStatement st1 =null;
        
        
        try {
        
            int row = urunler_tablosu.getSelectedRow();
            int satir=row+1;
            String secim_yap=(urunler_tablosu.getValueAt(row, 1).toString());
           
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/stok_takip", "root", "");
            
            String sorgu = "select * from urunler where id='"+satir+"'";
            //st = con.createStatement(); 
            st = con.createStatement();
            rs = st.executeQuery(sorgu);
            
            if(rs.last()){
                
                kategori_alani.setText(rs.getString("kategori"));
                ad_alani.setText(rs.getString("urunadi"));
                beden_alani.setText(rs.getString("beden"));
                renk_alani.setText(rs.getString("renk"));
                fiyat_alani.setText(rs.getString("fiyat"));
                adet_alani.setText(rs.getString("adet"));
                aciklama_alani.setText(rs.getString("aciklama"));
            }
            
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }

    }//GEN-LAST:event_urunler_tablosuMouseClicked

    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed
        
        try {
            
            int row = urunler_tablosu.getSelectedRow();            
            String secim=(urunler_tablosu.getValueAt(row, 0).toString());
            int satir=row+1;
            Class.forName("com.mysql.jdbc.Driver");

            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/stok_takip", "root", "");

            String sorgu = "UPDATE urunler SET kategori='"+kategori_alani.getText()+"'"
                    +",urunadi='"+ad_alani.getText()+"'"
                    +",beden='"+beden_alani.getText()+"'"
                    +",renk='"+renk_alani.getText()+"'"
                    +",fiyat='"+fiyat_alani.getText()+"'"
                    +",adet='"+adet_alani.getText()+"'"
                    +",aciklama='"+aciklama_alani.getText()+"' where id='"+satir+"'";
                    
          
            st = con.createStatement();
            st.executeUpdate(sorgu);

            JOptionPane.showMessageDialog(null, "Ürün Güncellemesi Tamamlanmıştır.");

            
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }
        
        UrunListeGuncelle();
        
    }//GEN-LAST:event_guncelleActionPerformed

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed
        
        urun_ekle a = new urun_ekle();
        a.setVisible(false);
        dispose();
        
    }//GEN-LAST:event_cikisActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        
    }//GEN-LAST:event_formWindowClosing

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        
        try {
            
            int row = urunler_tablosu.getSelectedRow();            
            String secim=(urunler_tablosu.getValueAt(row, 0).toString());
            int satir=row+1;
            
            Class.forName("com.mysql.jdbc.Driver");

            Connection con = null;
            Statement st = null;
            ResultSet rs = null;

            con = DriverManager.getConnection("jdbc:mysql://localhost/stok_takip", "root", "");

            String sorgu = "delete from urunler where id='"+satir+"'";
                    
          
            st = con.createStatement();
            st.executeUpdate(sorgu);

            JOptionPane.showMessageDialog(null, "Ürün Başarıyla Silinmiştir");

            
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
        }
        
        UrunListeGuncelle();
        
    }//GEN-LAST:event_silActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(urun_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(urun_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(urun_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(urun_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new urun_ekle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aciklama_alani;
    private javax.swing.JTextField ad_alani;
    private javax.swing.JTextField adet_alani;
    private javax.swing.JButton arama;
    private javax.swing.JTextField arama_alani;
    private javax.swing.JTextField beden_alani;
    private javax.swing.JButton cikis;
    private javax.swing.JButton ekle;
    private javax.swing.JTextField fiyat_alani;
    private javax.swing.JButton guncelle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kategori_alani;
    private javax.swing.JLabel lbl_adi;
    private javax.swing.JLabel lbl_filtrele;
    private javax.swing.JLabel lbl_fiyat;
    private javax.swing.JLabel lbl_fiyat1;
    private javax.swing.JLabel lbl_fiyat2;
    private javax.swing.JLabel lbl_kategori;
    private javax.swing.JLabel lbl_renk;
    private javax.swing.JLabel lbl_renk1;
    private javax.swing.JTextField renk_alani;
    private javax.swing.JButton sil;
    private javax.swing.JTable urunler_tablosu;
    // End of variables declaration//GEN-END:variables
}
