/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stok_takip_programi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author CASPER
 */
public class uye_ekle extends javax.swing.JFrame {

    /**
     * Creates new form uye_ekle
     */
    public uye_ekle() {
        
         super("Üye Ekle Formu");  
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_kategori = new javax.swing.JLabel();
        lbl_kadi = new javax.swing.JLabel();
        lbl_parola = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        kategori_alani = new javax.swing.JTextField();
        kullanici_adi = new javax.swing.JTextField();
        email_alani = new javax.swing.JTextField();
        uye_ekle = new javax.swing.JButton();
        sifre = new javax.swing.JPasswordField();
        cikis = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(410, 320));
        getContentPane().setLayout(null);

        lbl_kategori.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_kategori.setText("Kategori");
        getContentPane().add(lbl_kategori);
        lbl_kategori.setBounds(50, 40, 50, 17);

        lbl_kadi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_kadi.setText("Kullanıcı Adı");
        getContentPane().add(lbl_kadi);
        lbl_kadi.setBounds(40, 90, 68, 17);

        lbl_parola.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_parola.setText("Parola");
        getContentPane().add(lbl_parola);
        lbl_parola.setBounds(50, 140, 37, 17);

        lbl_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_email.setText("E-Posta");
        getContentPane().add(lbl_email);
        lbl_email.setBounds(50, 190, 47, 17);
        getContentPane().add(kategori_alani);
        kategori_alani.setBounds(130, 30, 170, 30);
        getContentPane().add(kullanici_adi);
        kullanici_adi.setBounds(130, 80, 170, 30);
        getContentPane().add(email_alani);
        email_alani.setBounds(130, 180, 170, 30);

        uye_ekle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uye_ekle.setText("Kaydet");
        uye_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uye_ekleActionPerformed(evt);
            }
        });
        getContentPane().add(uye_ekle);
        uye_ekle.setBounds(130, 240, 170, 34);
        getContentPane().add(sifre);
        sifre.setBounds(130, 130, 170, 30);

        cikis.setText("ÇIKIŞ");
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });
        getContentPane().add(cikis);
        cikis.setBounds(309, 10, 80, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stok_takip_programi/background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uye_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uye_ekleActionPerformed
        
            String kategori=kategori_alani.getText();
            String kullanici=kullanici_adi.getText();
            String parola=sifre.getText();
            String email=email_alani.getText();
                
            try {
                    
                if (kategori.equals("") || kullanici.equals("") || parola.equals("") || email.equals("")) {

                    JOptionPane.showMessageDialog(this, "Lütfen Boş Alanları Doldurunuz!");

                } else {            
                    Class.forName("com.mysql.jdbc.Driver");

                    Connection con = null;
                    Statement st = null;
                    ResultSet rs = null;
                    
                    con = DriverManager.getConnection("jdbc:mysql://localhost/stok_takip", "root", "");
                    st = con.createStatement();
                    
                    String sql = "INSERT INTO uyeler (kategori,kullanici,parola,email)" 
                            + " VALUES ('"+kategori+"', '"+kullanici+"', '"+parola+"', '"+email+"')";

                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Hoşgeldiniz " + kullanici);
            
                }
            
            } catch (ClassNotFoundException ex) {
                 JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

            } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
            }  
        
    }//GEN-LAST:event_uye_ekleActionPerformed

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed

        raporlar kapat = new raporlar();
        kapat.setVisible(false);
        dispose();
    }//GEN-LAST:event_cikisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uye_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uye_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uye_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uye_ekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uye_ekle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cikis;
    private javax.swing.JTextField email_alani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField kategori_alani;
    private javax.swing.JTextField kullanici_adi;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_kadi;
    private javax.swing.JLabel lbl_kategori;
    private javax.swing.JLabel lbl_parola;
    private javax.swing.JPasswordField sifre;
    private javax.swing.JButton uye_ekle;
    // End of variables declaration//GEN-END:variables
}
