/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stok_takip_programi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author CASPER
 */
public class uye_giris extends javax.swing.JFrame {

    /**
     * Creates new form uye_giris
     */
    public uye_giris() {
        
        super("Üye Girişi Formu");
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_kadi = new javax.swing.JLabel();
        lbl_sifre = new javax.swing.JLabel();
        kullanici_adi = new javax.swing.JTextField();
        sifre = new javax.swing.JPasswordField();
        giris = new javax.swing.JButton();
        sifre_unuttum = new javax.swing.JLabel();
        cikis = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(410, 310));
        getContentPane().setLayout(null);

        lbl_kadi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_kadi.setText("Kullanıcı Adı");
        getContentPane().add(lbl_kadi);
        lbl_kadi.setBounds(80, 100, 68, 17);

        lbl_sifre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_sifre.setText("Şifre");
        getContentPane().add(lbl_sifre);
        lbl_sifre.setBounds(80, 170, 26, 17);
        getContentPane().add(kullanici_adi);
        kullanici_adi.setBounds(170, 100, 170, 30);
        getContentPane().add(sifre);
        sifre.setBounds(170, 160, 170, 30);

        giris.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        giris.setText("Giriş");
        giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisActionPerformed(evt);
            }
        });
        getContentPane().add(giris);
        giris.setBounds(170, 220, 170, 36);

        sifre_unuttum.setText("Şifremi Unuttum");
        sifre_unuttum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sifre_unuttum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sifre_unuttumMouseClicked(evt);
            }
        });
        getContentPane().add(sifre_unuttum);
        sifre_unuttum.setBounds(220, 280, 93, 16);

        cikis.setText("ÇIKIŞ");
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });
        getContentPane().add(cikis);
        cikis.setBounds(309, 20, 80, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stok_takip_programi/background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(400, 300));
        jLabel1.setMinimumSize(new java.awt.Dimension(400, 300));
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisActionPerformed
        
            String kullanici=kullanici_adi.getText();
            String parola=sifre.getText();
                
            try {
                    
                if (kullanici.equals("") || parola.equals("")) {

                    JOptionPane.showMessageDialog(this, "Lütfen Boş Alanları Doldurunuz!");

                } else {            
                    Class.forName("com.mysql.jdbc.Driver");

                    Connection con = null;
                    Statement st = null;
                    ResultSet rs = null;
                    
                    con = DriverManager.getConnection("jdbc:mysql://localhost/stok_takip", "root", "");
                    st = con.createStatement();
                    
                    rs = st.executeQuery("select * from uyeler where kullanici='"+kullanici+"' and parola='"+parola+"'");
                    
                    if(rs.last()){
                        
                        if(rs.getString("kategori").equals("Müdür")){
                            raporlar ac = new raporlar();
                            ac.setVisible(true);
                        }
                        else if(rs.getString("kategori").equals("Satış Danışmanı")){
                            satislar ac = new satislar();
                            ac.setVisible(true);
                        }
                        else if(rs.getString("kategori").equals("Depocu")){
                            urun_ekle ac = new urun_ekle();
                            ac.setVisible(true);
                        }
                        
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Kullanıcı Adı veya Parola Hatalı! "); 
                    }
                }
            
            } catch (ClassNotFoundException ex) {
                 JOptionPane.showMessageDialog(null,"Hata: " + ex.toString());

            } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(this,"Veritabanına bağlantı sağlanamadı! " + ex.toString());
            }
        
    }//GEN-LAST:event_girisActionPerformed

    private void sifre_unuttumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sifre_unuttumMouseClicked
        
        unuttum goster = new unuttum();
        goster.setVisible(true);
        
    }//GEN-LAST:event_sifre_unuttumMouseClicked

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed

        raporlar kapat = new raporlar();
        kapat.setVisible(false);
        dispose();

    }//GEN-LAST:event_cikisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uye_giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uye_giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uye_giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uye_giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uye_giris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cikis;
    private javax.swing.JButton giris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField kullanici_adi;
    private javax.swing.JLabel lbl_kadi;
    private javax.swing.JLabel lbl_sifre;
    private javax.swing.JPasswordField sifre;
    private javax.swing.JLabel sifre_unuttum;
    // End of variables declaration//GEN-END:variables
}
